
version: '2'

services:
    db:
      image: mysql
      environment:
                - MYSQL_DATABASE=homestead
                - MYSQL_USER=homestead
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
      volumes:
            - ./db:/var/lib/mysql
      ports:
            - "3306:3306"
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
     ports:
            - "80:80"
     links:
            # for mysql container
            - "db:db"
volumes:
    db:
